language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    - llvm-toolchain-precise-3.6
    packages:
    - cmake
    - cmake-data
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-gfx1.2-dev
    - liblua5.2-dev
    - clang-3.6

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; export COMPILER=clang++-3.6; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl sdl_image sdl_gfx lua; fi

script: 
  - git submodule update
  - cd extlibs/wren
  - make
  - cd ../..
  - mkdir build
  - cd build
  - cmake ..
  - make

after_success:
  - echo Success

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
