language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    - llvm-toolchain-precise-3.6
    packages:
    - cmake
    - cmake-data
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-gfx1.2-dev
    - libsdl-ttf2.0-dev
    - liblua5.2-dev
    - clang-3.6
    - lcov

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then wget http://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tar xf SFML-2.4.0-linux-gcc-64-bit.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo cp -r SFML-2.4.0/lib/* /usr/local/lib/.; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo cp -r SFML-2.4.0/include/* /usr/local/include/.; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; export COMPILER=clang++-3.6; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install --user cpp-coveralls; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sfml sdl sdl_image sdl_gfx sdl_ttf lua lcov pyenv; export COMPILER=clang++; fi

  - if [ $TRAVIS_OS_NAME == osx ]; the eval "$(pyenv init -)"; fi
  - if [ $TRAVIS_OS_NAME == osx ]; the pyenv install 2.7.6; fi
  - if [ $TRAVIS_OS_NAME == osx ]; the pyenv global 2.7.6; fi
  - if [ $TRAVIS_OS_NAME == osx ]; the pyenv rehash; fi
  - if [ $TRAVIS_OS_NAME == osx ]; the pip install cpp-coveralls; fi
  - if [ $TRAVIS_OS_NAME == osx ]; the pyenv rehash; fi

script: 
  - git submodule update
  - cd extlibs/wren
  - make static
  - cd ../..
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER -DENABLE_CODE_COVERAGE=ON
  - make -j 64
  - make test
  - coveralls --gcov-options '\-lp'
after_success:
  - echo Success

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
