language: cpp

compiler:
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-cache search sdl dev; sudo apt-get install -y cmake libsdl-dev libsdl_image-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cmake sdl sdl_image sdl_gfx; fi

script: 
  - mkdir build
  - cd build
  - cmake ..
  - make

after_success:
  - echo Success

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
